version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: node1
    ports:
    - 5672:5672
    - 15672:15672
    volumes:
    - rabbitmq:/var/lib/rabbitmq
  filebeat:
    image: docker.elastic.co/beats/filebeat-oss:7.8.0
    container_name: filebeat
    depends_on:
      - elasticsearch
    entrypoint: filebeat -e -strict.perms=false
    volumes:
    - filebeat:/usr/share/filebeat/data
    - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    - ../ads-microservice/log:/var/log/ads:ro
    - ../auth-microservice/log:/var/log/auth:ro
    - ../geocoder-microservice/log:/var/log/geocoder:ro
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.8.0
    container_name: elascticsearch
    volumes:
    - elasticsearch:/usr/share/elasticsearch/data
    - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.8.0
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
    - 5601:5601

volumes:
  rabbitmq:
  filebeat:
  elasticsearch:
