global:
  scrape_interval: 30s
scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']
  - job_name: 'ads'
    static_configs:
      - targets: ['host.docker.internal:3000']
  - job_name: 'auth'
    static_configs:
      - targets: ['host.docker.internal:3010']
  - job_name: 'geocoder'
    static_configs:
      - targets: ['host.docker.internal:3020']

